AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Layout/IndentArray:
  EnforcedStyle: consistent

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Enabled: false
