language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - "main"

cache: bundler

sudo: false

git:
  depth: 10
