language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
branches:
  only:
    - "master"
    - "/^release-/"
before_install: gem install bundler
cache: bundler
sudo: false
git:
  depth: 10
